### ISSUE TITLE
ValueError: mean is not a valid value for reduction

### ISSUE THREAD

**Issue by p6jain** [facebookresearch/kbc#7]
Command used:
python kbc/learn.py --dataset FB15K --model ComplEx --rank 2000 --optimizer Adagrad --learning_rate 1e-2 --batch_size 100 --regularizer N3 --reg 5e-3 --max_epochs 10 --valid 1

Pytorch version:
>>> torch.__version__
'0.4.1.post2'

Error:
Traceback (most recent call last):
  File "kbc/learn.py", line 129, in <module>
    cur_loss = optimizer.epoch(examples)
  File "/pytorch_kbc/kbc/kbc/optimizers.py", line 42, in epoch
    l_fit = loss(predictions, truth)
  File "/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 862, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/nn/functional.py", line 1550, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/nn/functional.py", line 1407, in nll_loss
    return torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
  File "/home/prachi/anaconda3/envs/kbc_env2/lib/python3.6/site-packages/torch/nn/functional.py", line 30, in get_enum
    raise ValueError(reduction + " is not a valid value for reduction")
ValueError: mean is not a valid value for reduction

**Comment by timlacroix** [comment]
Hi,

you have to update pytorch to the latest version, I removed the 0.4.1 requirement in the requirements.txt
